# Generated by Django 4.2.5 on 2023-11-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='Movie',
        ),
    ]
