# Generated by Django 4.2.5 on 2023-11-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('movies', '0002_alter_movies_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
